# Generated by Django 2.1.7 on 2019-04-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20190407_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(default='Добавить', verbose_name='Описание'),
        ),
    ]
