# Generated by Django 2.2 on 2019-05-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_bookincart'),
        ('reference', '0006_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, help_text='Минск, ул. Первая, 7-77', null=True, verbose_name='Адрес доставки')),
                ('email', models.EmailField(blank=True, help_text='user@gmail.com', max_length=254, null=True, verbose_name='Электронная почта')),
                ('phone', models.CharField(help_text='+375-29-111-11-11', max_length=17, verbose_name='Контактный телефон')),
                ('created_day', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в корзину')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.Cart', verbose_name='Корзина')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reference.OrderStatus', verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
