# Generated by Django 2.2 on 2019-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190605_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comments',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, help_text='Минск, ул. Первая, 7-77', max_length=50, null=True, verbose_name='Адрес доставки'),
        ),
    ]
