# Generated by Django 2.2 on 2019-05-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0004_remove_genre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название книги')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/img', verbose_name='Обложка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('issue_year', models.IntegerField(verbose_name='Год издания')),
                ('page', models.IntegerField(verbose_name='Страниц')),
                ('binding', models.CharField(max_length=200, verbose_name='Переплет')),
                ('size', models.CharField(max_length=200, verbose_name='Формат')),
                ('isbn', models.CharField(max_length=200, verbose_name='ISBN')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('age_rest', models.CharField(max_length=10, verbose_name='Возрастные ораничения')),
                ('num_book', models.IntegerField(verbose_name='Количество книг в наличии')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна для заказа')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('authors', models.ManyToManyField(related_name='Book', to='reference.Author', verbose_name='Автор')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='reference.Genre', verbose_name='Жанр')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='reference.Publisher', verbose_name='Издательство')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='reference.Serie', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
