# Generated by Django 2.1.7 on 2019-04-07 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0004_remove_genre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название книги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('issue_year', models.IntegerField(verbose_name='Год издания')),
                ('page', models.IntegerField(verbose_name='Страниц')),
                ('binding', models.CharField(max_length=200, verbose_name='Переплет')),
                ('size', models.CharField(max_length=200, verbose_name='Формат')),
                ('isbn', models.CharField(max_length=200, verbose_name='ISBN')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('age_rest', models.CharField(max_length=10, verbose_name='Возрастные ораничения')),
                ('num_book', models.IntegerField(verbose_name='Количество книг в наличии')),
                ('available', models.BooleanField(default=True, verbose_name='Доступна для заказа')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('authors', models.ManyToManyField(to='reference.Author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='reference.Genre', verbose_name='Жанр')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='reference.Publisher')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='reference.Serie', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
