# Generated by Django 2.2 on 2019-05-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default=1, upload_to='media/img', verbose_name='Обложка'),
            preserve_default=False,
        ),
    ]
